Updated build script so it can now build for cedarview as well as armada38x.   Needs build_sdk.sh changes from the QNAP branch in the sdk

diff --git a/build/SynologyNAS/toolkit/source/megacmdpkg/SynoBuildConf/build b/build/SynologyNAS/toolkit/source/megacmdpkg/SynoBuildConf/build
--- a/build/SynologyNAS/toolkit/source/megacmdpkg/SynoBuildConf/build
+++ b/build/SynologyNAS/toolkit/source/megacmdpkg/SynoBuildConf/build
@@ -4,15 +4,18 @@ mkdir ./MEGAcmd/sdk/sdk_build
 mkdir ./MEGAcmd/sdk/sdk_build/install
 mkdir ./MEGAcmd/sdk/sdk_build/install/lib
 
-# machine=armada38x for DS218j
+AUTOMAKE_OPTIONS="no-dependencies"
+
+#achine=armada38x for DS218j.  This variable short-circuits ./config for those projects that use it.
 export MACHINE=$PLATFORM_ABBR
 export CUSTOM_CONFIG_ARGS="$ConfigOpt"
 export AM_LIBTOOLFLAGS='--tag=CXX'
+export SPECIAL_OPENSSL_CONFIG_PARAMS="no-asm no-ssl no-ssl2 no-ssl3 no-ssl3-method no-weak-ssl-ciphers"
 
 export CC=$CC
 export CXX=$CXX
 export LD=$LD
-export CFLAGS="$CFLAGS -O3 -fPIC -fexceptions -fvisibility=hidden"
+export CFLAGS="$CFLAGS -O3 -fexceptions -fvisibility=hidden -static"
 export CXXFLAGS="-std=c++11 $CFLAGS"
 export AR=$AR
 export NM=$NM
@@ -37,21 +40,45 @@ echo CFLAGS was $CFLAGS
 export CFLAGS=`echo $CFLAGS | sed -e 's/-D[^ ][^ ]*//g' `
 echo CFLAGS now $CFLAGS
 
+#we need to specify the platform specially for OpenSSL
+case $PLATFORM_ABBR in
+armada38x)
+  export OS_COMPILER_FOR_OPENSSL=linux-x86_64
+  ;;
+cedarview)
+  export OS_COMPILER_FOR_OPENSSL=linux-generic32
+  ;;
+esac
+
 echo ---------- env set up --------------------
 env
 echo ---------- env set up --------------------
 
+
 cd MEGAcmd/sdk
 pwd
-echo executing ./contrib/build_sdk.sh -a -e -g -n -q -x "$CUSTOM_CONFIG_ARGS" 
-./contrib/build_sdk.sh -a -e -g -n -q -x "$CUSTOM_CONFIG_ARGS" 2>&1 | tee /mybuildlogs-sdkbuild.out
 
-echo "libtool could not link it so we do it ourselves. Including Zen and MediaInfo somehow reference a nonexistent path /home/chingfen in the Synology libtool libraries. If we left those out it would make the lib ok."
-echo "we make the lib using $AR directly, with and output the same name src/libmega.la that satisfies the configure script for MEGAcmd."
-$AR -rcs src/libmega.la `find src -name "*.o"` `find sdk_build -name "*.a"`
+mkdir -p norecurse
+mv norecurse/* .
 
-mkdir norecurse
-mv ./Makefile norecurse
+./contrib/build_sdk.sh -a -e -g -I -n -q -R -X -C "$CUSTOM_CONFIG_ARGS" -O $OS_COMPILER_FOR_OPENSSL -S "$SPECIAL_OPENSSL_CONFIG_PARAMS" 2>&1 | tee /mybuildlogs-sdkbuild.out
+
+if ! [ -e src/libmega.la ] ; then
+    echo "libtool could not link it so we do it ourselves. Including Zen and MediaInfo somehow reference a nonexistent path /home/chingfen in the Synology libtool libraries. If we left those out it would make the lib ok."
+    echo "we make the lib using $AR directly, with and output the same name src/libmega.la that satisfies the configure script for MEGAcmd."
+    $AR -rcs src/libmega.a `find src -name "*.o"` `find sdk_build -name "*.a"`
+    #MEGAcmd configure wants to see a .la file too
+    cp ./src/libmega.a ./src/libmega.la
+    cp ./src/libmega* ./sdk_build/install/lib/
+fi
+
+if ! [ -e ./src/libmega.la ] ; then
+   echo "SDK build failed"
+   exit 1
+fi
+
+
+mv ./Makefile* norecurse
 mv ./config* norecurse
 cd ..
 
@@ -64,7 +91,7 @@ sh autogen.sh 2>&1 | tee /mybuildlogs-autogen2.out
 ./configure --enable-static --with-cryptopp $CUSTOM_CONFIG_ARGS  2>&1 | tee /mybuildlogs-configure2.out 
 
 export INCLUDES="-I/source/megacmdpkg/MEGAcmd/sdk/sdk_build/install/include -I/source/megacmdpkg/MEGAcmd/sdk/include/ -I/source/megacmdpkg/MEGAcmd/sdk/include/mega/posix"
-make SUBDIRS='' 2>&1 | tee /mybuildlogs-make2.out
+make SUBDIRS='' DEFS='' 2>&1 | tee /mybuildlogs-make2.out
 
 echo "-------------------------------seems autotools cannot build mega-cmd-server though the other two succeed"
 echo "-------------------------------above it does not like our directly built non-libtool library, but prior to adding Zen and MediaInfo it failed anyway even with the libtool built libmega.la"
@@ -72,9 +99,22 @@ echo "-------------------------------the problem then was that it did not like t
 echo "-------------------------------either way building it directly at this point does the trick"
 pwd
 
-echo "executing command $CXX $CXXFLAGS src/megacmd.cpp src/comunicationsmanager.cpp         src/megacmdutils.cpp src/configurationmanager.cpp         src/megacmdlogger.cpp src/megacmdsandbox.cpp src/listeners.cpp         src/megacmdexecuter.cpp         src/comunicationsmanagerportsockets.cpp src/comunicationsmanagerfilesockets.cpp -Isdk/include -Isdk/include/mega/posix -Isdk/sdk_build/install/include  sdk/src/libmega.la sdk/sdk_build/install/lib/libcryptopp.a sdk/sdk_build/install/lib/libmediainfo.a sdk/sdk_build/install/lib/libzen.a  sdk/sdk_build/install/lib/libcurl.a sdk/sdk_build/install/lib/libcares.a sdk/sdk_build/install/lib/libssl.a sdk/sdk_build/install/lib/libcrypto.a sdk/sdk_build/install/lib/libfreeimage.a sdk/sdk_build/install/lib/libsqlite3.a -lpthread -ldl -lrt -o mega-cmd-server"
+env
 
-$CXX $CXXFLAGS src/megacmd.cpp src/comunicationsmanager.cpp         src/megacmdutils.cpp src/configurationmanager.cpp         src/megacmdlogger.cpp src/megacmdsandbox.cpp src/listeners.cpp         src/megacmdexecuter.cpp         src/comunicationsmanagerportsockets.cpp src/comunicationsmanagerfilesockets.cpp -Isdk/include -Isdk/include/mega/posix -Isdk/sdk_build/install/include  sdk/src/libmega.la sdk/sdk_build/install/lib/libcryptopp.a sdk/sdk_build/install/lib/libmediainfo.a sdk/sdk_build/install/lib/libzen.a  sdk/sdk_build/install/lib/libcurl.a sdk/sdk_build/install/lib/libcares.a sdk/sdk_build/install/lib/libssl.a sdk/sdk_build/install/lib/libcrypto.a sdk/sdk_build/install/lib/libfreeimage.a sdk/sdk_build/install/lib/libsqlite3.a -lpthread -ldl -lrt -o mega-cmd-server
+if ! [ -e mega-cmd-server ] ; then
+    echo "Attempt to build mega-cmd-server manually"
+    $CXX $CXXFLAGS src/megacmd.cpp src/comunicationsmanager.cpp         src/megacmdutils.cpp src/configurationmanager.cpp         src/megacmdlogger.cpp src/megacmdsandbox.cpp src/listeners.cpp         src/megacmdexecuter.cpp         src/comunicationsmanagerportsockets.cpp src/comunicationsmanagerfilesockets.cpp -Isdk/include -Isdk/include/mega/posix -Isdk/sdk_build/install/include  sdk/sdk_build/install/lib/libmega.a sdk/sdk_build/install/lib/libcryptopp.a sdk/sdk_build/install/lib/libmediainfo.a sdk/sdk_build/install/lib/libzen.a  sdk/sdk_build/install/lib/libcurl.a sdk/sdk_build/install/lib/libcares.a sdk/sdk_build/install/lib/libssl.a sdk/sdk_build/install/lib/libcrypto.a sdk/sdk_build/install/lib/libfreeimage.a sdk/sdk_build/install/lib/libsqlite3.a -lpthread -ldl -lrt -o mega-cmd-server
+fi
+
+if ! [ -e mega-cmd ] ; then
+    echo "Attempt to build mega-cmd manually"
+    $CXX $CXXFLAGS src/megacmdshell/*.cpp -Isdk/include -Isdk/include/mega/posix -Isdk/sdk_build/install/include  sdk/sdk_build/install/lib/libmega.a sdk/sdk_build/install/lib/libcryptopp.a    sdk/sdk_build/install/lib/libcurl.a sdk/sdk_build/install/lib/libcares.a sdk/sdk_build/install/lib/libssl.a sdk/sdk_build/install/lib/libcrypto.a  sdk/sdk_build/install/lib/libsqlite3.a -lpthread -ldl -lrt sdk/sdk_build/install/lib/libz.a ./sdk/sdk_build/install/lib/libreadline.a ./sdk/sdk_build/install/lib/libtermcap.a -o mega-cmd
+fi
+
+if ! [ -e mega-exec ] ; then
+    echo "Attempt to build mega-exec manually"
+    $CXX $CXXFLAGS  src/client/*.cpp src/megacmdshell/megacmdshellcommunications.cpp -Isdk/include -Isdk/include/mega/posix -Isdk/sdk_build/install/include  sdk/sdk_build/install/lib/libmega.a sdk/sdk_build/install/lib/libcryptopp.a    sdk/sdk_build/install/lib/libcurl.a sdk/sdk_build/install/lib/libcares.a sdk/sdk_build/install/lib/libssl.a sdk/sdk_build/install/lib/libcrypto.a  sdk/sdk_build/install/lib/libsqlite3.a -lpthread -ldl -lrt sdk/sdk_build/install/lib/libz.a -o mega-exec
+fi
 
 echo "final return code: $?"
 echo "outputs should be 3 files: mega-cmd mega-cmd-server mega-exec.  ls output: "
