Allow sharing of test-results directory for legacy tests with host.

diff --git a/jenkinsfile/Jenkinsfile_MR_linux b/jenkinsfile/Jenkinsfile_MR_linux
--- a/jenkinsfile/Jenkinsfile_MR_linux
+++ b/jenkinsfile/Jenkinsfile_MR_linux
@@ -152,15 +152,17 @@ pipeline {
 			}
 			steps{
 			    lock(label: 'testing_accounts_megacmd', variable: 'MEGA_EMAIL', quantity: 1, resource: null){
-				script {
-				    try {
-					sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL --env MEGA_PWD --rm -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 5 && mkdir /tmp/tests && cd /tmp/tests && bash -x /usr/local/bin/${TEST_SCRIPT}'"
-				    } catch(e) {
-					if (env.SANITIZERS == 'tsan'){
-                                            echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
-                                        } else {
-                                            sh "exit 1"
-                                        }
+				dir('test-results') {
+				    script {
+					try {
+					    sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL --env MEGA_PWD --rm --mount type=bind,src='${megacmd_sources_workspace}/test-results',target=/tmp/test-results -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 5 && mkdir /tmp/tests && cd /tmp/tests && bash -x /usr/local/bin/${TEST_SCRIPT}'"
+					} catch(e) {
+					    if (env.SANITIZERS == 'tsan'){
+						echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
+                                            } else {
+						sh "exit 1"
+                                            }
+					}
 				    }
 				}
 			    }
@@ -193,15 +195,17 @@ pipeline {
 			}
 			steps{
 			    lock(label: 'testing_accounts_megacmd', variable: 'MEGA_EMAIL', quantity: 1, resource: null){
-				script {
-				    try {
-					sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL --env MEGA_PWD --rm -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 1 && mkdir /tmp/tests && cd /tmp/tests && python3 /usr/local/bin/${TEST_SCRIPT}'"
-				    } catch(e) {
-					if (env.SANITIZERS == 'tsan'){
-                                            echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
-                                        } else {
-                                            sh "exit 1"
-                                        }
+				dir('test-results') {
+				    script {
+					try {
+					    sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL --env MEGA_PWD --rm --mount type=bind,src='${megacmd_sources_workspace}/test-results',target=/tmp/test-results -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 1 && mkdir /tmp/tests && cd /tmp/tests && python3 /usr/local/bin/${TEST_SCRIPT}'"
+					} catch(e) {
+					    if (env.SANITIZERS == 'tsan'){
+						echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
+                                            } else {
+						sh "exit 1"
+                                            }
+					}
 				    }
 				}
 			    }
