Run multiple account legacy tests as well.

diff --git a/jenkinsfile/Jenkinsfile_MR_linux b/jenkinsfile/Jenkinsfile_MR_linux
--- a/jenkinsfile/Jenkinsfile_MR_linux
+++ b/jenkinsfile/Jenkinsfile_MR_linux
@@ -128,7 +128,7 @@ pipeline {
                 }
             }
         }
-	stage('Run legacy MEGAcmd integration tests') {
+	stage('Run legacy MEGAcmd integration test scripts requiring a single account') {
 	    matrix {
 		axes {
 		    axis {
@@ -140,30 +140,64 @@ pipeline {
 			values 'megacmd_find_test.sh', 'megacmd_put_test.sh', 'megacmd_rm_test.sh', 'megacmd_find_test.py', 'megacmd_put_test.py', 'megacmd_rm_test.py'
 		    }
 		}
-		stages{
-		    stage('Run MEGAcmd integration test scripts requiring a single account') {
-			environment{
-			    MEGA_EMAIL=''
-			    MEGA_PWD=credentials('MEGACMD_TESTS_PASSWORD')
-			    ASAN_OPTIONS="atexit=1,print_stats=1,log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-asan-report"
-                            TSAN_OPTIONS="log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-tsan-report"
-                            UBSAN_OPTIONS="log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-ubsan-report"
-			}
-			steps{
-			    lock(label: 'testing_accounts_megacmd', variable: 'MEGA_EMAIL', quantity: 1, resource: null){
-				dir('test-results') {
-				    script {
-					try {
-					    sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL --env MEGA_PWD --rm -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 1 && mkdir /tmp/tests && cd /tmp/tests && /usr/local/bin/${TEST_SCRIPT}'"
-					} catch(e) {
-					    if (env.SANITIZERS == 'tsan'){
-						echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
-                                            } else {
-						sh "exit 1"
-                                            }
-					}
-				    }
+		environment {
+		    MEGA_EMAIL=''
+		    MEGA_PWD=credentials('MEGACMD_TESTS_PASSWORD')
+		    ASAN_OPTIONS="atexit=1,print_stats=1,log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-asan-report"
+                    TSAN_OPTIONS="log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-tsan-report"
+                    UBSAN_OPTIONS="log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-ubsan-report"
+		}
+		steps{
+		    lock(label: 'testing_accounts_megacmd', variable: 'MEGA_EMAIL', quantity: 1, resource: null){
+			dir('test-results') {
+			    script {
+				try {
+				    sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL --env MEGA_PWD --rm -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 1 && mkdir /tmp/tests && cd /tmp/tests && /usr/local/bin/${TEST_SCRIPT}'"
+				} catch(e) {
+				    if (env.SANITIZERS == 'tsan'){
+					echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
+                                    } else {
+					sh "exit 1"
+                                    }
 				}
+			    }
+			}
+		    }
+		}
+	    }
+	}
+	stage('Run legacy MEGAcmd integration test scripts requiring two accounts') {
+	    matrix  {
+		axes {
+		    axis {
+			name 'SANITIZERS'
+			values 'ubsan', 'asan', 'tsan'
+		    }
+		    axis {
+			name 'TEST_SCRIPT'
+			values 'megacmd_get_test.py', 'megacmd_misc_test.py'
+		    }
+		}
+	    }
+	    environment {
+		MEGA_PWD=credentials('MEGACMD_TESTS_PASSWORD')
+		MEGA_PWD_AUX=credentials('MEGACMD_TESTS_PASSWORD')
+		ASAN_OPTIONS="atexit=1,print_stats=1,log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-asan-report"
+                TSAN_OPTIONS="log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-tsan-report"
+                UBSAN_OPTIONS="log_path=/tmp/test-results/megacmd-${TEST_SCRIPT}-ubsan-report"
+	    }
+	    steps {
+		lock(label: 'testing_accounts_megacmd', variable: 'MEGA_EMAIL', quantity: 2, resource: null) {
+		    dir('test-results') {
+			script {
+			    try {
+				sh "docker run --user \$(id -u):\$(id -g) --env ASAN_OPTIONS --env TSAN_OPTIONS --env HOME=/tmp --env MEGA_EMAIL=${MEGA_EMAIL0} --env=MEGA_EMAIL_AUX=${MEGA_EMAIL1} --env MEGA_PWD --env MEGA_PWD_AUX--env MEGA_PWD --rm -- meganz/megacmd-autotools-${SANITIZERS}:${env.BUILD_NUMBER} /usr/bin/bash -c '/usr/local/bin/mega-cmd-server > /dev/null & sleep 1 && mkdir /tmp/tests && cd /tmp/tests && /usr/local/bin/mega-rm -r -f / && /usr/local/bin/${TEST_SCRIPT}'"
+			    } catch(e) {
+				if (env.SANITIZERS == 'tsan'){
+				    echo "${env.SANITIZERS} sanitizer build are expected to fail for now, will keep the build as successful"
+                                } else {
+				    sh "exit 1"
+                                }
 			    }
 			}
 		    }
