remove parallelization of unit & integration tests in windows

diff --git a/jenkinsfile/Jenkinsfile_MR_windows b/jenkinsfile/Jenkinsfile_MR_windows
--- a/jenkinsfile/Jenkinsfile_MR_windows
+++ b/jenkinsfile/Jenkinsfile_MR_windows
@@ -138,63 +138,59 @@ pipeline {
                 sh "cmake --install ${BUILD_DIR} --config Debug"
             }
         }
-        stage('Run tests'){
-            parallel {
-                stage('Run unit tests'){
-                    environment{
-                        INSTALL_DIR  = "${megacmd_sources_workspace}\\cmdbuild\\Debug"
-                    }
-                    options{
-                        timeout(time: 3, unit: 'HOURS')
-                    }
-                    steps{
-                        sh "echo Running tests"
-                        bat """
-                            ${INSTALL_DIR}\\mega-cmd-tests-unit.exe --gtest_shuffle --gtest_output=xml:${megacmd_sources_workspace}\\megacmd-unit-tests.xml
+        stage('Run unit tests'){
+            environment{
+                INSTALL_DIR  = "${megacmd_sources_workspace}\\cmdbuild\\Debug"
+            }
+            options{
+                timeout(time: 3, unit: 'HOURS')
+            }
+            steps{
+                sh "echo Running tests"
+                bat """
+                    ${INSTALL_DIR}\\mega-cmd-tests-unit.exe --gtest_shuffle --gtest_output=xml:${megacmd_sources_workspace}\\megacmd-unit-tests.xml
+                    if %ERRORLEVEL% NEQ 0 exit 1
+                    exit %ERROR_VAL%
+                    """
+                }
+                post{
+                always{
+                    junit(testResults: "**/*-unit-*.xml")
+                }
+            }
+        }
+        stage('Run integration tests'){
+            environment{
+                INSTALL_DIR  = "${megacmd_sources_workspace}\\cmdbuild\\Debug"
+                MEGACMD_TEST_USER=''
+                MEGACMD_TEST_PASS=credentials('MEGACMD_TESTS_PASSWORD')
+            }
+            options{
+                timeout(time: 3, unit: 'HOURS')
+            }
+            steps{
+                //bat "dir ${windows_sources_workspace}\\..\\3rdparty\\\\vcpkg\\\\installed\\\\x64-windows-mega\\\\debug\\\\bin"
+                lock(label: 'testing_accounts_megacmd', variable: 'MEGACMD_TEST_USER', quantity: 1, resource: null) {
+                    script {
+                        try {
+                            bat """
+                            if %ERRORLEVEL% NEQ 0 set ERRORLEVEL=0
+                            ${INSTALL_DIR}\\mega-cmd-tests-integration.exe --gtest_stack_trace_depth=10 --gmock_verbose=info --gtest_shuffle --gtest_output=xml:${megacmd_sources_workspace}\\megacmd-integration-tests.xml
                             if %ERRORLEVEL% NEQ 0 exit 1
                             exit %ERROR_VAL%
                             """
-                        }
-                        post{
-                        always{
-                            junit(testResults: "**/*-unit-*.xml")
+                        } catch (e) {
+                            echo "Integration tests on Windows are expected to fail for now."
                         }
                     }
                 }
-                stage('Run integration tests'){
-                    environment{
-                        INSTALL_DIR  = "${megacmd_sources_workspace}\\cmdbuild\\Debug"
-                        MEGACMD_TEST_USER=''
-                        MEGACMD_TEST_PASS=credentials('MEGACMD_TESTS_PASSWORD')
-                    }
-                    options{
-                        timeout(time: 3, unit: 'HOURS')
-                    }
-                    steps{
-                        //bat "dir ${windows_sources_workspace}\\..\\3rdparty\\\\vcpkg\\\\installed\\\\x64-windows-mega\\\\debug\\\\bin"
-                        lock(label: 'testing_accounts_megacmd', variable: 'MEGACMD_TEST_USER', quantity: 1, resource: null) {
-                            script {
-                                try {
-                                    bat """
-                                    if %ERRORLEVEL% NEQ 0 set ERRORLEVEL=0
-                                    ${INSTALL_DIR}\\mega-cmd-tests-integration.exe --gtest_stack_trace_depth=10 --gmock_verbose=info --gtest_shuffle --gtest_output=xml:${megacmd_sources_workspace}\\megacmd-integration-tests.xml
-                                    if %ERRORLEVEL% NEQ 0 exit 1
-                                    exit %ERROR_VAL%
-                                    """
-                                } catch (e) {
-                                    echo "Integration tests on Windows are expected to fail for now."
-                                }
-                            }
-                        }
-                    }
-                    post{
-                        always{
-                            junit(testResults: "**/*-integration-*.xml", allowEmptyResults: true)
-                            bat """
-                                rmdir ${INSTALL_DIR}\\.megaCmd /s /q
-                            """
-                        }
-                    }
+            }
+            post{
+                always{
+                    junit(testResults: "**/*-integration-*.xml", allowEmptyResults: true)
+                    bat """
+                        rmdir ${INSTALL_DIR}\\.megaCmd /s /q
+                    """
                 }
             }
         }
