Added package files and instructions on how to build a QNAP package that can be installed on a QNAP NAS.  Also added verbose level switch for diagnosing issues on the NAS.

diff --git a/build/QNAP_NAS/build b/build/QNAP_NAS/build
--- a/build/QNAP_NAS/build
+++ b/build/QNAP_NAS/build
@@ -21,9 +21,9 @@ export CUSTOM_CONFIG_ARGS="--host=arm-none-linux-gnueabi --disable-dependency-tr
 export CC=${CROSS_COMPILE}gcc
 export CXX=${CROSS_COMPILE}g++
 export LD=${CROSS_COMPILE}ld
-export CFLAGS="$CFLAGS -O3 -fPIC -fexceptions -fvisibility=hidden -fsigned-char "
-#export CXXFLAGS="-std=c++11 $CXXFLAGS $CFLAGS"
-export CXXFLAGS="$CXXFLAGS $CFLAGS"
+export CFLAGS="$CFLAGS -O3 -fPIC -fexceptions -fvisibility=hidden -fsigned-char -DNDEBUG"
+export CPPFLAGS="-DNDEBUG"
+export CXXFLAGS="$CXXFLAGS $CFLAGS -DNDEBUG"
 export AR=${CROSS_COMPILE}ar
 export NM=${CROSS_COMPILE}nm
 export STRIP=${CROSS_COMPILE}strip
@@ -62,21 +62,23 @@ pwd
 mkdir -p norecurse
 mv norecurse/* .
 
-echo executing ./contrib/build_sdk.sh -a -e -f -g -I -q -x "$CUSTOM_CONFIG_ARGS" 
+echo executing ./contrib/build_sdk.sh -a -e -f -g -I -q -X -C "$CUSTOM_CONFIG_ARGS" -O linux-generic32
+
 #ultimately after overcoming many build challenges, we still can't build freeimage, as it turns out it uses __sync builtins, but they fail to link.  Hence the -f
-./contrib/build_sdk.sh -a -e -g -f -I -n -q -R -x "$CUSTOM_CONFIG_ARGS" -0 2>&1 | tee $MEGA_CMD_DIR/mybuildlogs-sdkbuild.out
+./contrib/build_sdk.sh -a -e -g -f -I -n -q -R -X -C"$CUSTOM_CONFIG_ARGS" -O linux-generic32 -0 2>&1 | tee $MEGA_CMD_DIR/mybuildlogs-sdkbuild.out
 
+if ! [ -e src/libmega.la ] ; then
+    echo "libtool could not link it so we do it ourselves. Including Zen and MediaInfo somehow reference a nonexistent path /home/slava in the Synology libtool libraries. If we left those out it would make the lib ok."
+    echo "we make the lib using $AR directly, with and output the same name src/libmega.la that satisfies the configure script for MEGAcmd."
+    rm -f src/libmega.la
+    $AR -rcs ./src/libmega.la `find src -name "*.o"` `find sdk_build -name "*.a"`
+    cp ./src/libmega.a ./src/libmega.la
+    cp ./src/libmega* ./sdk_build/install/lib/
+fi
 
-echo "libtool could not link it so we do it ourselves. Including Zen and MediaInfo somehow reference a nonexistent path /home/slava in the Synology libtool libraries. If we left those out it would make the lib ok."
-echo "we make the lib using $AR directly, with and output the same name src/libmega.la that satisfies the configure script for MEGAcmd."
-rm -f src/libmega.la
-$AR -rcs src/libmega.la `find src -name "*.o"` `find sdk_build -name "*.a"`
-
-if [ $? -ne 0 ] ; then
+if ! [ -e ./src/libmega.la ] ; then
+   echo "SDK build failed"
    exit 1
-else
-   cp src/libmega.la ./sdk_build/install/lib/
-   cp ./sdk_build/install/lib/libmega.la ./sdk_build/install/lib/libmega.a
 fi
 
 mv ./Makefile* norecurse/
@@ -109,4 +111,8 @@ $CXX $CXXFLAGS  src/client/*.cpp src/megacmdshell/megacmdshellcommunications.cpp
 
 echo "outputs should be 3 files: mega-cmd mega-cmd-server mega-exec.  ls output: "
 ls mega-cmd mega-cmd-server mega-exec
+
+mkdir -p install
+cp src/client/mega-* install/
+cp mega-cmd mega-exec mega-cmd-server install/
 
